### ISSUE TITLE
"Borrowing" the code

### ISSUE THREAD

**Issue by timyerg** [suchapalaver/fastas2kmers#1]
Hi!
Thank you for the script. It works great.
I want to integrate your script into mine. I will comment there in the code that I used your code and provide a link to your GitHub.
I hope that it is fine.
Is there any other way I can cite your work?

**Comment by suchapalaver** [comment]
Awesome! I encourage you to check out my `krust` repository as that's a Rust implementation that might also be interesting.

I'd love to see your combined work once it's out in the open. Thanks for the heads up.
